feat: add support for subtitles extension change (close #1)

diff --git a/shisper b/shisper
--- a/shisper
+++ b/shisper
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.0.1 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.0.5 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -36,7 +36,7 @@ shisper_usage() {
   printf "%s\n" "Commands:"
   printf "  %s   Play a media file with generated subtitles / transcriptions\n" "play       "
   printf "  %s   Generate subtitles / transcriptions using your audio inputs\n" "stream     "
-  printf "  %s   Generate subtitles and transcriptions for any kind of media file\n" "transcribe "
+  printf "  %s   Generate subtitles / transcriptions for any kind of media file\n" "transcribe "
   printf "  %s   Show the entire config file\n" "list       "
   printf "  %s   Generate bash completions\n" "completions"
   echo
@@ -78,7 +78,7 @@ shisper_play_usage() {
   fi
 
   printf "%s\n" "Usage:"
-  printf "  shisper play MEDIA_FILE\n"
+  printf "  shisper play MEDIA_FILE [SUB_FORMAT]\n"
   printf "  shisper play --help | -h\n"
   echo
 
@@ -97,6 +97,12 @@ shisper_play_usage() {
     # :argument.usage
     printf "  %s\n" "MEDIA_FILE"
     printf "    Video or audio file\n"
+    echo
+
+    # :argument.usage
+    printf "  %s\n" "SUB_FORMAT"
+    printf "    Format for subtitles / transcription\n    Supported values\n    txt vtt srt lrc words csv json\n"
+    printf "    Default: srt\n"
     echo
 
   fi
@@ -134,17 +140,17 @@ shisper_stream_usage() {
 # :command.usage
 shisper_transcribe_usage() {
   if [[ -n $long_usage ]]; then
-    printf "shisper transcribe - Generate subtitles and transcriptions for any kind of media file\n"
+    printf "shisper transcribe - Generate subtitles / transcriptions for any kind of media file\n"
     echo
 
   else
-    printf "shisper transcribe - Generate subtitles and transcriptions for any kind of media file\n"
+    printf "shisper transcribe - Generate subtitles / transcriptions for any kind of media file\n"
     echo
 
   fi
 
   printf "%s\n" "Usage:"
-  printf "  shisper transcribe MEDIA_FILE\n"
+  printf "  shisper transcribe MEDIA_FILE [SUB_FORMAT]\n"
   printf "  shisper transcribe --help | -h\n"
   echo
 
@@ -163,6 +169,12 @@ shisper_transcribe_usage() {
     # :argument.usage
     printf "  %s\n" "MEDIA_FILE"
     printf "    Video or audio file\n"
+    echo
+
+    # :argument.usage
+    printf "  %s\n" "SUB_FORMAT"
+    printf "    Format for subtitles / transcription\n    Supported values\n    txt vtt srt lrc words csv json\n"
+    printf "    Default: srt\n"
     echo
 
     # :command.usage_examples
@@ -472,13 +484,14 @@ extract_audio() {
 
 play_media() {
   local media_file="$1"
+  local sub_format="$2"
 
   echo -e "[$(cyan_bold " INFO ")] Playing file with generated transcription ..."
   echo -e "${media_file}"
 
   mpv \
     --quiet \
-    --sub-file="${media_file%%.*}.srt" \
+    --sub-file="${media_file%%.*}.${sub_format}" \
     "${media_file}" 1>/dev/null
 
   echo -e "[$(green_bold "  OK  ")] Playback completed."
@@ -517,10 +530,11 @@ check_models() {
   fi
 }
 
-check_srt() {
+check_sub() {
   local media_file="$1"
+  local sub_format="$2"
 
-  if [[ ! -f "${media_file%%.*}.srt" ]]; then
+  if [[ ! -f "${media_file%%.*}.${sub_format}" ]]; then
     echo -e "[$(red_bold " FAILED ")] Generated transcription not found"
     exit 1
   fi
@@ -540,24 +554,25 @@ run_whisper() {
   local media_file="$1"
   local model_file="$2"
   local lang="$3"
+  local sub_format="$4"
 
   whisper.cpp \
     --file "${media_file%%.*}" \
     --language "${lang}" \
     --model "${MODEL_PATH}/${model_file}" \
-    --output-srt \
+    --output-"${sub_format}" \
     --no-timestamps >/dev/null
 
   echo -e "[$(green_bold "  OK  ")] Completed"
   echo -e "[$(cyan_bold " INFO ")] Generated transcription is:"
-  echo -e "${media_file%%.*}.srt"
+  echo -e "${media_file%%.*}.${sub_format}"
 }
 
 run_whisper_stream() {
   local model_file="$1"
   local lang="$2"
 
-  if [ "${lang}" == "auto" ]; then
+  if [[ "${lang}" == "auto" ]]; then
     lang="en"
   fi
 
@@ -575,10 +590,11 @@ shisper_play_command() {
   #!/usr/bin/env bash
 
   media_file="${args[media_file]}"
+  sub_format="${args[sub_format]}"
 
   check_media "${media_file}"
-  check_srt "${media_file}"
-  play_media "${media_file}"
+  check_sub "${media_file}" "${sub_format}"
+  play_media "${media_file}" "${sub_format}"
 }
 
 # :command.function
@@ -599,15 +615,17 @@ shisper_transcribe_command() {
   # src/transcribe_command.sh
   #!/usr/bin/env bash
 
+  lang="$(config_get lang)"
   media_file="${args[media_file]}"
   model_file="ggml-$(config_get model).bin"
-  lang="$(config_get lang)"
+  # sub_format="$(config_get sub_format)"
+  sub_format="${args[sub_format]}"
 
   check_media "${media_file}"
   check_media_type "${media_file}"
   extract_audio "${media_file}"
   check_models "${model_file}"
-  run_whisper "${media_file}" "${model_file}" "${lang}"
+  run_whisper "${media_file}" "${model_file}" "${lang}" "${sub_format}"
   clean_temp_file "${media_file}"
 
 }
@@ -615,12 +633,14 @@ shisper_transcribe_command() {
 # :command.function
 shisper_list_command() {
   # src/list_command.sh
+  #!/usr/bin/env bash
+
   # Using the standard library (lib/config.sh) to show the entire config file
   config_show
 
   # Or to iterate through keys
   for key in $(config_keys); do
-    echo "$key === $(config_get "$key")"
+    echo "$key === $(config_get "${key}")"
   done
 
 }
@@ -666,8 +686,6 @@ parse_requirements() {
     printf "missing required environment variable: MODEL_PATH\n" >&2
     exit 1
   fi
-
-  # :command.dependencies_filter
 
   # :command.command_filter
   action=${1:-}
@@ -764,8 +782,6 @@ shisper_play_parse_requirements() {
     esac
   done
 
-  # :command.dependencies_filter
-
   # :command.command_filter
   action="play"
 
@@ -786,6 +802,10 @@ shisper_play_parse_requirements() {
 
           args['media_file']=$1
           shift
+        elif [[ -z ${args['sub_format']+x} ]]; then
+
+          args['sub_format']=$1
+          shift
         else
           printf "invalid argument: %s\n" "$key" >&2
           exit 1
@@ -798,9 +818,12 @@ shisper_play_parse_requirements() {
 
   # :command.required_args_filter
   if [[ -z ${args['media_file']+x} ]]; then
-    printf "missing required argument: MEDIA_FILE\nusage: shisper play MEDIA_FILE\n" >&2
+    printf "missing required argument: MEDIA_FILE\nusage: shisper play MEDIA_FILE [SUB_FORMAT]\n" >&2
     exit 1
   fi
+
+  # :command.default_assignments
+  [[ -n ${args['sub_format']:-} ]] || args['sub_format']="srt"
 
 }
 
@@ -821,8 +844,6 @@ shisper_stream_parse_requirements() {
 
     esac
   done
-
-  # :command.dependencies_filter
 
   # :command.command_filter
   action="stream"
@@ -868,8 +889,6 @@ shisper_transcribe_parse_requirements() {
     esac
   done
 
-  # :command.dependencies_filter
-
   # :command.command_filter
   action="transcribe"
 
@@ -890,6 +909,10 @@ shisper_transcribe_parse_requirements() {
 
           args['media_file']=$1
           shift
+        elif [[ -z ${args['sub_format']+x} ]]; then
+
+          args['sub_format']=$1
+          shift
         else
           printf "invalid argument: %s\n" "$key" >&2
           exit 1
@@ -902,9 +925,12 @@ shisper_transcribe_parse_requirements() {
 
   # :command.required_args_filter
   if [[ -z ${args['media_file']+x} ]]; then
-    printf "missing required argument: MEDIA_FILE\nusage: shisper transcribe MEDIA_FILE\n" >&2
+    printf "missing required argument: MEDIA_FILE\nusage: shisper transcribe MEDIA_FILE [SUB_FORMAT]\n" >&2
     exit 1
   fi
+
+  # :command.default_assignments
+  [[ -n ${args['sub_format']:-} ]] || args['sub_format']="srt"
 
 }
 
@@ -925,8 +951,6 @@ shisper_list_parse_requirements() {
 
     esac
   done
-
-  # :command.dependencies_filter
 
   # :command.command_filter
   action="list"
@@ -972,8 +996,6 @@ shisper_completions_parse_requirements() {
     esac
   done
 
-  # :command.dependencies_filter
-
   # :command.command_filter
   action="completions"
 
@@ -1002,7 +1024,7 @@ shisper_completions_parse_requirements() {
 
 # :command.initialize
 initialize() {
-  version="0.2"
+  version="0.2.1"
   long_usage=''
   set -e
 
@@ -1038,51 +1060,11 @@ run() {
   parse_requirements "${input[@]}"
 
   case "$action" in
-    "play")
-      if [[ ${args['--help']:-} ]]; then
-        long_usage=yes
-        shisper_play_usage
-      else
-        shisper_play_command
-      fi
-      ;;
-
-    "stream")
-      if [[ ${args['--help']:-} ]]; then
-        long_usage=yes
-        shisper_stream_usage
-      else
-        shisper_stream_command
-      fi
-      ;;
-
-    "transcribe")
-      if [[ ${args['--help']:-} ]]; then
-        long_usage=yes
-        shisper_transcribe_usage
-      else
-        shisper_transcribe_command
-      fi
-      ;;
-
-    "list")
-      if [[ ${args['--help']:-} ]]; then
-        long_usage=yes
-        shisper_list_usage
-      else
-        shisper_list_command
-      fi
-      ;;
-
-    "completions")
-      if [[ ${args['--help']:-} ]]; then
-        long_usage=yes
-        shisper_completions_usage
-      else
-        shisper_completions_command
-      fi
-      ;;
-
+    "play") shisper_play_command ;;
+    "stream") shisper_stream_command ;;
+    "transcribe") shisper_transcribe_command ;;
+    "list") shisper_list_command ;;
+    "completions") shisper_completions_command ;;
   esac
 }
 
