chore: allow to choose model from cli args (close #4)

diff --git a/shisper b/shisper
--- a/shisper
+++ b/shisper
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.1.10 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.2.3 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -17,15 +17,7 @@ version_command() {
 
 # :command.usage
 shisper_usage() {
-  if [[ -n $long_usage ]]; then
-    printf "shisper - A quick & dirty script to generate subs and transcriptions for your multimedia files.\n"
-    echo
-
-  else
-    printf "shisper - A quick & dirty script to generate subs and transcriptions for your multimedia files.\n"
-    echo
-
-  fi
+  printf "shisper - A quick & dirty script to generate subs and transcriptions for your multimedia files.\n\n"
 
   printf "%s\n" "Usage:"
   printf "  shisper COMMAND\n"
@@ -41,7 +33,7 @@ shisper_usage() {
   echo
 
   # :command.long_usage
-  if [[ -n $long_usage ]]; then
+  if [[ -n "$long_usage" ]]; then
     printf "%s\n" "Options:"
 
     # :command.usage_fixed_flags
@@ -58,7 +50,7 @@ shisper_usage() {
     # :environment_variable.usage
     printf "  %s\n" "MODEL_PATH"
     printf "    Set the model home path\n"
-    printf "    Default: ${HOME}/.local/share/whispercpp\n"
+    printf "    %s\n" "Default: ${HOME}/.local/share/whispercpp"
     echo
 
   fi
@@ -66,24 +58,23 @@ shisper_usage() {
 
 # :command.usage
 shisper_play_usage() {
-  if [[ -n $long_usage ]]; then
-    printf "shisper play - Play a media file with generated subtitles / transcriptions\n"
-    echo
-
-  else
-    printf "shisper play - Play a media file with generated subtitles / transcriptions\n"
-    echo
-
-  fi
+  printf "shisper play - Play a media file with generated subtitles / transcriptions\n\n"
 
   printf "%s\n" "Usage:"
-  printf "  shisper play MEDIA_FILE [SUB_FORMAT]\n"
+  printf "  shisper play MEDIA_FILE [OPTIONS]\n"
   printf "  shisper play --help | -h\n"
   echo
 
   # :command.long_usage
-  if [[ -n $long_usage ]]; then
+  if [[ -n "$long_usage" ]]; then
     printf "%s\n" "Options:"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "--format, -f FORMAT"
+    printf "    Format for subtitles / transcription\n    \n    Supported values:\n    txt vtt srt lrc words csv json json-full\n"
+    printf "    %s\n" "Default: srt"
+    echo
 
     # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
@@ -96,12 +87,6 @@ shisper_play_usage() {
     # :argument.usage
     printf "  %s\n" "MEDIA_FILE"
     printf "    Video or audio file\n"
-    echo
-
-    # :argument.usage
-    printf "  %s\n" "SUB_FORMAT"
-    printf "    Format for subtitles / transcription\n    Supported values\n    txt vtt srt lrc words csv json\n"
-    printf "    Default: srt\n"
     echo
 
   fi
@@ -109,24 +94,35 @@ shisper_play_usage() {
 
 # :command.usage
 shisper_transcribe_usage() {
-  if [[ -n $long_usage ]]; then
-    printf "shisper transcribe - Generate subtitles / transcriptions for any kind of media file\n"
-    echo
-
-  else
-    printf "shisper transcribe - Generate subtitles / transcriptions for any kind of media file\n"
-    echo
-
-  fi
+  printf "shisper transcribe - Generate subtitles / transcriptions for any kind of media file\n\n"
 
   printf "%s\n" "Usage:"
-  printf "  shisper transcribe MEDIA_FILE [SUB_FORMAT]\n"
+  printf "  shisper transcribe MEDIA_FILE [OPTIONS]\n"
   printf "  shisper transcribe --help | -h\n"
   echo
 
   # :command.long_usage
-  if [[ -n $long_usage ]]; then
+  if [[ -n "$long_usage" ]]; then
     printf "%s\n" "Options:"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "--format, -f FORMAT"
+    printf "    Format for subtitles / transcription\n    \n    Supported values:\n    txt vtt srt lrc words csv json\n"
+    printf "    %s\n" "Default: srt"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "--lang, -l LANG"
+    printf "    Spoken language ('auto' for auto-detect)\n"
+    printf "    %s\n" "Default: auto"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "--model, -m MODEL"
+    printf "    Whisper models converted in ggml format\n    \n    Supported values:\n      tiny tiny.en base base.en small small.en medium medium.en large-v1\n    large-v2 large\n      note: large corresponds to the latest Large v3 model\n"
+    printf "    %s\n" "Default: tiny"
+    echo
 
     # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
@@ -141,15 +137,9 @@ shisper_transcribe_usage() {
     printf "    Video or audio file\n"
     echo
 
-    # :argument.usage
-    printf "  %s\n" "SUB_FORMAT"
-    printf "    Format for subtitles / transcription\n    Supported values\n    txt vtt srt lrc words csv json\n"
-    printf "    Default: srt\n"
-    echo
-
     # :command.usage_examples
     printf "%s\n" "Examples:"
-    printf "  shisper transcribe my_video.mkv\n"
+    printf "  shisper transcribe --model large my_video.mkv\n"
     printf "  shisper transcribe my_audio.mp3\n"
     echo
 
@@ -158,16 +148,7 @@ shisper_transcribe_usage() {
 
 # :command.usage
 shisper_list_usage() {
-  if [[ -n $long_usage ]]; then
-    printf "shisper list - Show the entire config file\n"
-    echo
-
-  else
-    printf "shisper list - Show the entire config file\n"
-    echo
-
-  fi
-
+  printf "shisper list - Show the entire config file\n\n"
   printf "Alias: l\n"
   echo
 
@@ -177,7 +158,7 @@ shisper_list_usage() {
   echo
 
   # :command.long_usage
-  if [[ -n $long_usage ]]; then
+  if [[ -n "$long_usage" ]]; then
     printf "%s\n" "Options:"
 
     # :command.usage_fixed_flags
@@ -191,16 +172,10 @@ shisper_list_usage() {
 # :command.usage
 shisper_completions_usage() {
   if [[ -n $long_usage ]]; then
-    printf "shisper completions\n"
-    echo
-
-    printf "  Generate bash completions\n  Usage: eval \"\$(shisper completions)\"\n"
-    echo
-
+    printf "shisper completions\n\n"
+    printf "  Generate bash completions\n  Usage: eval \"\$(shisper completions)\"\n\n"
   else
-    printf "shisper completions - Generate bash completions\n"
-    echo
-
+    printf "shisper completions - Generate bash completions\n\n"
   fi
 
   printf "%s\n" "Usage:"
@@ -209,7 +184,7 @@ shisper_completions_usage() {
   echo
 
   # :command.long_usage
-  if [[ -n $long_usage ]]; then
+  if [[ -n "$long_usage" ]]; then
     printf "%s\n" "Options:"
 
     # :command.usage_fixed_flags
@@ -229,7 +204,7 @@ shisper_completions_usage() {
 # :command.normalize_input
 # :command.normalize_input_function
 normalize_input() {
-  local arg flags passthru
+  local arg passthru flags
   passthru=false
 
   while [[ $# -gt 0 ]]; do
@@ -331,106 +306,6 @@ blue_underlined() { print_in_color "\e[4;34m" "$*"; }
 magenta_underlined() { print_in_color "\e[4;35m" "$*"; }
 cyan_underlined() { print_in_color "\e[4;36m" "$*"; }
 
-# src/lib/config.sh
-config_init() {
-  if [[ ! -f "/etc/shisper/config.ini" ]]; then
-    CONFIG_FILE=${CONFIG_FILE:=${HOME}/.shisperrc}
-    [[ -f "$CONFIG_FILE" ]] || touch "$CONFIG_FILE"
-  else
-    CONFIG_FILE="/etc/shisper/config.ini"
-  fi
-}
-
-config_get() {
-  local key=$1
-  local regex="^$key *= *(.+)$"
-  local value=""
-
-  config_init
-
-  while IFS= read -r line || [ -n "$line" ]; do
-    if [[ $line =~ $regex ]]; then
-      value="${BASH_REMATCH[1]}"
-      break
-    fi
-  done <"$CONFIG_FILE"
-
-  echo "$value"
-}
-
-config_set() {
-  local key=$1
-  shift
-  local value="$*"
-
-  config_init
-
-  local regex="^($key) *= *.+$"
-  local output=""
-  local found_key=""
-  local newline
-
-  while IFS= read -r line || [ -n "$line" ]; do
-    newline=$line
-    if [[ $line =~ $regex ]]; then
-      found_key="${BASH_REMATCH[1]}"
-      newline="$key = $value"
-      output="$output$newline\n"
-    elif [[ $line ]]; then
-      output="$output$line\n"
-    fi
-  done <"$CONFIG_FILE"
-
-  if [[ -z $found_key ]]; then
-    output="$output$key = $value\n"
-  fi
-
-  printf "%b\n" "$output" >"$CONFIG_FILE"
-}
-
-config_del() {
-  local key=$1
-
-  local regex="^($key) *="
-  local output=""
-
-  config_init
-
-  while IFS= read -r line || [ -n "$line" ]; do
-    if [[ $line ]] && [[ ! $line =~ $regex ]]; then
-      output="$output$line\n"
-    fi
-  done <"$CONFIG_FILE"
-
-  printf "%b\n" "$output" >"$CONFIG_FILE"
-}
-
-config_show() {
-  config_init
-  cat "$CONFIG_FILE"
-}
-
-config_keys() {
-  local regex="^([a-zA-Z0-9_\-\/\.]+) *="
-
-  config_init
-
-  local keys=()
-  local key
-
-  while IFS= read -r line || [ -n "$line" ]; do
-    if [[ $line =~ $regex ]]; then
-      key="${BASH_REMATCH[1]}"
-      keys+=("$key")
-    fi
-  done <"$CONFIG_FILE"
-  echo "${keys[@]}"
-}
-
-config_has_key() {
-  [[ $(config_get "$1") ]]
-}
-
 # src/lib/media.sh
 #!/usr/bin/env bash
 
@@ -507,16 +382,16 @@ check_media() {
 }
 
 check_models() {
-  local model="$1"
+  local model_file="$1"
 
   if [[ ! -d "${MODEL_PATH}" ]]; then
     mkdir -p "${MODEL_PATH}"
   fi
 
-  if [[ -f "${MODEL_PATH}/ggml-${model}.bin" ]]; then
-    echo -e "[$(cyan_bold " INFO ")] ${MODEL_PATH}/ggml-${model}.bin is present"
+  if [[ -f "${MODEL_PATH}/ggml-${model_file}.bin" ]]; then
+    echo -e "[$(cyan_bold " INFO ")] ${MODEL_PATH}/ggml-${model_file}.bin is present"
   else
-    download_model "${model}"
+    download_model_file "${model_file}"
   fi
 }
 
@@ -549,7 +424,7 @@ run_whisper() {
   whisper.cpp \
     --file "${media_file%.*}" \
     --language "${lang}" \
-    --model "${MODEL_PATH}/ggml-${model}.bin" \
+    --model "${MODEL_PATH}/ggml-${model_file}.bin" \
     --output-"${sub_format}" \
     --no-timestamps >/dev/null
 
@@ -576,12 +451,10 @@ shisper_play_command() {
 shisper_transcribe_command() {
   # src/transcribe_command.sh
   #!/usr/bin/env bash
-
-  lang="$(config_get lang)"
   media_file="${args[media_file]}"
-  model="$(config_get model)"
-  # sub_format="$(config_get sub_format)"
-  sub_format="${args[sub_format]}"
+  lang="${args[--lang]}"
+  model="${args[--model]}"
+  sub_format="${args[--format]}"
 
   check_media "${media_file}"
   check_media_type "${media_file}"
@@ -621,7 +494,8 @@ shisper_completions_command() {
 parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
-    case "${1:-}" in
+    key="$1"
+    case "$key" in
       --version | -v)
         version_command
         exit
@@ -720,7 +594,8 @@ parse_requirements() {
 shisper_play_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
-    case "${1:-}" in
+    key="$1"
+    case "$key" in
       --help | -h)
         long_usage=yes
         shisper_play_usage
@@ -741,6 +616,19 @@ shisper_play_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
+      # :flag.case
+      --format | -f)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--format']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--format requires an argument: --format, -f FORMAT" >&2
+          exit 1
+        fi
+        ;;
 
       -?*)
         printf "invalid option: %s\n" "$key" >&2
@@ -754,10 +642,6 @@ shisper_play_parse_requirements() {
         if [[ -z ${args['media_file']+x} ]]; then
           args['media_file']=$1
           shift
-        # :argument.case
-        elif [[ -z ${args['sub_format']+x} ]]; then
-          args['sub_format']=$1
-          shift
         else
           printf "invalid argument: %s\n" "$key" >&2
           exit 1
@@ -770,12 +654,13 @@ shisper_play_parse_requirements() {
 
   # :command.required_args_filter
   if [[ -z ${args['media_file']+x} ]]; then
-    printf "missing required argument: MEDIA_FILE\nusage: shisper play MEDIA_FILE [SUB_FORMAT]\n" >&2
+    printf "missing required argument: MEDIA_FILE\nusage: shisper play MEDIA_FILE [OPTIONS]\n" >&2
+
     exit 1
   fi
 
   # :command.default_assignments
-  [[ -n ${args['sub_format']:-} ]] || args['sub_format']="srt"
+  [[ -n ${args['--format']:-} ]] || args['--format']="srt"
 
 }
 
@@ -783,7 +668,8 @@ shisper_play_parse_requirements() {
 shisper_transcribe_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
-    case "${1:-}" in
+    key="$1"
+    case "$key" in
       --help | -h)
         long_usage=yes
         shisper_transcribe_usage
@@ -804,6 +690,47 @@ shisper_transcribe_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
+      # :flag.case
+      --format | -f)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--format']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--format requires an argument: --format, -f FORMAT" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --lang | -l)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--lang']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--lang requires an argument: --lang, -l LANG" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --model | -m)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--model']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--model requires an argument: --model, -m MODEL" >&2
+          exit 1
+        fi
+        ;;
 
       -?*)
         printf "invalid option: %s\n" "$key" >&2
@@ -817,10 +744,6 @@ shisper_transcribe_parse_requirements() {
         if [[ -z ${args['media_file']+x} ]]; then
           args['media_file']=$1
           shift
-        # :argument.case
-        elif [[ -z ${args['sub_format']+x} ]]; then
-          args['sub_format']=$1
-          shift
         else
           printf "invalid argument: %s\n" "$key" >&2
           exit 1
@@ -833,12 +756,15 @@ shisper_transcribe_parse_requirements() {
 
   # :command.required_args_filter
   if [[ -z ${args['media_file']+x} ]]; then
-    printf "missing required argument: MEDIA_FILE\nusage: shisper transcribe MEDIA_FILE [SUB_FORMAT]\n" >&2
+    printf "missing required argument: MEDIA_FILE\nusage: shisper transcribe MEDIA_FILE [OPTIONS]\n" >&2
+
     exit 1
   fi
 
   # :command.default_assignments
-  [[ -n ${args['sub_format']:-} ]] || args['sub_format']="srt"
+  [[ -n ${args['--format']:-} ]] || args['--format']="srt"
+  [[ -n ${args['--lang']:-} ]] || args['--lang']="auto"
+  [[ -n ${args['--model']:-} ]] || args['--model']="tiny"
 
 }
 
@@ -846,7 +772,8 @@ shisper_transcribe_parse_requirements() {
 shisper_list_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
-    case "${1:-}" in
+    key="$1"
+    case "$key" in
       --help | -h)
         long_usage=yes
         shisper_list_usage
@@ -890,7 +817,8 @@ shisper_list_parse_requirements() {
 shisper_completions_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
-    case "${1:-}" in
+    key="$1"
+    case "$key" in
       --help | -h)
         long_usage=yes
         shisper_completions_usage
