chore: check for run-time dependencies

diff --git a/shisper b/shisper
--- a/shisper
+++ b/shisper
@@ -895,6 +895,19 @@ initialize() {
   export MODEL_PATH="${MODEL_PATH:-${HOME}/.local/share/whispercpp}"
 
   # src/initialize.sh
+  required_executables=(whisper.cpp ffmpeg mpv)
+
+  check_requirements() {
+    for executable in "${required_executables[@]}"; do
+      if ! command -v "${executable}" &>/dev/null; then
+        echo -e "[$(red_bold " FAILED ")] ${executable} executable is required"
+        exit 1
+      fi
+
+    done
+  }
+
+  check_requirements
 
 }
 
